name: job_download

on:
  push:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname

      - name: Step-2 - Checkout
        uses: actions/checkout@v5.0.1

      - name: Step-3
        run: |
          echo `pwd` >> artifact1.txt
          ls -ltr
          hostname

      - name: upload artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: artifact-1
          path: ./artifact1.txt
  job2:
    name: job2
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step-4
        run: |
          pwd 
          ls -ltr
      - name: telecharger artefact 
        uses: actions/download-artifact@v6.0.0
        with:
          name: artifact-1
      - name: validation du download
        run: |
          pwd 
          ls -ltr
  job3:
    name: job3
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Creation repertoire pour telechargement
        run: |
          mkdir -p artifact-1
      - name: Verification du repertoire actuel
        run: |
          pwd
          ls -ltr
      - name: Telechargement de artifact-1
        uses: actions/download-artifact@v6.0.0
        with:
          name: artifact-1
          path: artifact-1
      - name: Verification du repertoire actuel apres telechargement
        run: |
          pwd
          echo "Verification du repertoire artifact-1"
          ls -ltr artifact-1
