name: test-actions
on: push
jobs:
  test-job:
    name: test-job1
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Salut actions!"

      - name: verification du runner
        run: cat /etc/os-release
